spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oppo_camera
    username: root
    password: weiyujie123
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#安卓->java 文件上传位置
fileUploadLocation: /root/projects/oppo_camera/androidPictures/
#fileUploadLocation: /home/wyj/Public/androidPictures/
#fileUploadLocation: /root/myproject/oppo_camera/androidPictures/
#fileUploadLocation: src/main/resources/androidPictures/ 不能用这个路径，用了出错

#python->java 脚本文件接收位置
fileReceiveLocation: /root/projects/oppo_camera/pythonProcessResult/
#fileReceiveLocation: /home/wyj/Public/processResult/
#fileReceiveLocation: /root/myproject/oppo_camera/pythonProcessResult/

mapper:
  identity: MYSQL

server:
  tomcat:
    max-http-post-size: -1
  max-http-header-size: 102400
